
version: '3.5'
services:
  dynamodb:
    container_name: dynamo-local
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    networks:
      - local-api-network
networks:
  local-api-network:
    name: local-api-network
    driver: bridge